name: Test

on: [push, pull_request]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.arch }}

    strategy:
      matrix:
        include:
          - arch: armv7
            distro: ubuntu_latest
          - arch: aarch64
            distro: ubuntu_latest
          - arch: s390x
            distro: ubuntu_latest
          - arch: ppc64le
            distro: ubuntu_latest
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          submodules: true
          set-safe-directory: true

      - uses: uraimo/run-on-arch-action@v2.2.0
        name: Build
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          githubToken: ${{ github.token }}

          install: |
            apt-get update -y
            apt-get install -y automake libtool autoconf autotools-dev git make gcc libyajl-dev libssl-dev libfsverity-dev pkg-config

            find $(pwd) -name '.git' -exec bash -c 'git config --global --add safe.directory ${0%/.git}' {} \;

          run: |
            ./autogen.sh
            ./configure CFLAGS='-Wall -Werror'
            make -j $(nproc)

  clang-formatter:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: install dependencies
      run: |
            sudo apt-get update -y
            sudo apt-get install -y make clang-format

    - name: check formatting
      run: |
            sudo docker build -t clang-format hacking/clang-format
            sudo docker run --rm -w /src -v ${PWD}:/src clang-format
